# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.rousette.org.uk
title: But She's A Girl
subtitle: Femina geekoides
author: bsag
simple_search: http://google.com/search

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/butshesagirl
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /blog
port: 4000
permalink: /archives/:title
source: source
destination: public/blog
plugins: plugins
code_dir: downloads/code
category_dir: tags
category_title_prefix: 'Tag: '
category_meta_description_prefix: 'Tag: '
markdown: rdiscount
pygments: false

paginate: 10 # Posts per page on the blog index
recent_posts: 5 # Posts in the sidebar Recent Posts section

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_user: bsag
twitter_tweet_count: 5
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google Plus
google_plus_one: true
google_plus_one_size: medium

# Pinboard
pinboard_user: bsag
pinboard_count: 5

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: bsag

# Google Analytics
google_analytics_tracking_id:
